// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOeNIusj9n-fUaQVCpHCNe56EJAh0htQ',
    appId: '1:927326149647:web:cd5f8c4938d12f535e177a',
    messagingSenderId: '927326149647',
    projectId: 'diaa-fc2d3',
    authDomain: 'diaa-fc2d3.firebaseapp.com',
    storageBucket: 'diaa-fc2d3.firebasestorage.app',
    measurementId: 'G-6JWM9NGS45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJvzmUnkQdfyaIUdueMboIR_YsoBlxpM8',
    appId: '1:927326149647:android:5e0d54102ae022165e177a',
    messagingSenderId: '927326149647',
    projectId: 'diaa-fc2d3',
    storageBucket: 'diaa-fc2d3.firebasestorage.app',
  );
}
